//
//  GHUserRepos.swift
//  GitHubUsersRepos
//
//  Created by Sirisha Dudiki on 10/10/19.
//  Copyright © 2019 GitHubUsersRepos. All rights reserved.
//
//{
//  "id": 50504570,
//  "node_id": "MDEwOlJlcG9zaXRvcnk1MDUwNDU3MA==",
//  "name": "myFirstSwiftCOde",
//  "full_name": "sirishadudiki/myFirstSwiftCOde",
//  "private": false,
//  "owner": {
//    "login": "sirishadudiki",
//    "id": 16917792,
//    "node_id": "MDQ6VXNlcjE2OTE3Nzky",
//    "avatar_url": "https://avatars2.githubusercontent.com/u/16917792?v=4",
//    "gravatar_id": "",
//    "url": "https://api.github.com/users/sirishadudiki",
//    "html_url": "https://github.com/sirishadudiki",
//    "followers_url": "https://api.github.com/users/sirishadudiki/followers",
//    "following_url": "https://api.github.com/users/sirishadudiki/following{/other_user}",
//    "gists_url": "https://api.github.com/users/sirishadudiki/gists{/gist_id}",
//    "starred_url": "https://api.github.com/users/sirishadudiki/starred{/owner}{/repo}",
//    "subscriptions_url": "https://api.github.com/users/sirishadudiki/subscriptions",
//    "organizations_url": "https://api.github.com/users/sirishadudiki/orgs",
//    "repos_url": "https://api.github.com/users/sirishadudiki/repos",
//    "events_url": "https://api.github.com/users/sirishadudiki/events{/privacy}",
//    "received_events_url": "https://api.github.com/users/sirishadudiki/received_events",
//    "type": "User",
//    "site_admin": false
//  },
//  "html_url": "https://github.com/sirishadudiki/myFirstSwiftCOde",
//  "description": "my first swift git set up",
//  "fork": false,
//  "url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde",
//  "forks_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/forks",
//  "keys_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/keys{/key_id}",
//  "collaborators_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/collaborators{/collaborator}",
//  "teams_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/teams",
//  "hooks_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/hooks",
//  "issue_events_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/issues/events{/number}",
//  "events_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/events",
//  "assignees_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/assignees{/user}",
//  "branches_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/branches{/branch}",
//  "tags_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/tags",
//  "blobs_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/git/blobs{/sha}",
//  "git_tags_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/git/tags{/sha}",
//  "git_refs_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/git/refs{/sha}",
//  "trees_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/git/trees{/sha}",
//  "statuses_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/statuses/{sha}",
//  "languages_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/languages",
//  "stargazers_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/stargazers",
//  "contributors_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/contributors",
//  "subscribers_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/subscribers",
//  "subscription_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/subscription",
//  "commits_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/commits{/sha}",
//  "git_commits_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/git/commits{/sha}",
//  "comments_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/comments{/number}",
//  "issue_comment_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/issues/comments{/number}",
//  "contents_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/contents/{+path}",
//  "compare_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/compare/{base}...{head}",
//  "merges_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/merges",
//  "archive_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/{archive_format}{/ref}",
//  "downloads_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/downloads",
//  "issues_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/issues{/number}",
//  "pulls_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/pulls{/number}",
//  "milestones_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/milestones{/number}",
//  "notifications_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/notifications{?since,all,participating}",
//  "labels_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/labels{/name}",
//  "releases_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/releases{/id}",
//  "deployments_url": "https://api.github.com/repos/sirishadudiki/myFirstSwiftCOde/deployments",
//  "created_at": "2016-01-27T12:03:35Z",
//  "updated_at": "2016-01-27T12:26:55Z",
//  "pushed_at": "2016-01-27T15:09:06Z",
//  "git_url": "git://github.com/sirishadudiki/myFirstSwiftCOde.git",
//  "ssh_url": "git@github.com:sirishadudiki/myFirstSwiftCOde.git",
//  "clone_url": "https://github.com/sirishadudiki/myFirstSwiftCOde.git",
//  "svn_url": "https://github.com/sirishadudiki/myFirstSwiftCOde",
//  "homepage": null,
//  "size": 22,
//  "stargazers_count": 0,
//  "watchers_count": 0,
//  "language": "Swift",
//  "has_issues": true,
//  "has_projects": true,
//  "has_downloads": true,
//  "has_wiki": true,
//  "has_pages": false,
//  "forks_count": 0,
//  "mirror_url": null,
//  "archived": false,
//  "disabled": false,
//  "open_issues_count": 0,
//  "license": null,
//  "forks": 0,
//  "open_issues": 0,
//  "watchers": 0,
//  "default_branch": "master"
//}

import Foundation

struct GHUserRepos : Decodable {
    let id : Int64
    
}
